[tool.pyrefly]
strict = true

python_version = "3.11"
venv_path = "."
venv = ".venv"

exclude = [
    "**/node_modules",
    "**/build",
    "**/dist"
]

[tool.pyrefly.plugins]
pydantic = true
pytorch_tensors = true

[tool.ruff]
target-version = "py311"

line-length = 79

[tool.ruff.lint]
select = ["E", "F", "I"]